services:
  
  postgis:
    image: postgis/postgis:latest
    container_name: postgis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_ANON_ROLE: ${DB_ANON_ROLE}
      DB_SCHEMA: ${DB_SCHEMA}
    ports:
      - 0.0.0.0:${POSTGRES_PORT}:5432
    volumes:
      - ${POSTGRES_DATA_DIR:-./postgres-data}:/var/lib/postgresql/data
      - ./scripts/initdb-postgis.sh:/docker-entrypoint-initdb.d/initdb-postgis.sh
    networks:
      - gis-net
    restart: unless-stopped

  postgrest:
    container_name: postgrest
    image: postgrest/postgrest:latest
    ports:
      - ${POSTGREST_PORT}:3000
    environment:
      - PGRST_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgis:5432/${POSTGRES_DB}
      - PGRST_DB_SCHEMA=${DB_SCHEMA}
      # The database role to use when no client authentication is provided
      - PGRST_DB_ANON_ROLE=${DB_ANON_ROLE}
      # Overrides the base URL used within the OpenAPI self-documentation hosted at the API root path
      - PGRST_OPENAPI_SERVER_PROXY_URI=http://localhost:3000
    networks:
      - gis-net
    depends_on:
      - postgis
  
  # martin:
  #   image: ghcr.io/maplibre/martin:latest
  #   container_name: martin_tileserver
  #   restart: unless-stopped
  #   ports:
  #     - 0.0.0.0:${MARTIN_PORT}:3000
  #   environment:
  #     - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgis:5432/${POSTGRES_DB}
    
  #   networks:
  #     - gis-net
  #   depends_on:
  #     - postgis
    
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        PGADMIN_LISTEN_PORT: 80
    ports:
        - 0.0.0.0:${PGADMIN_PORT}:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - gis-net
    depends_on:
      - postgis

  # swagger:
  #   image: swaggerapi/swagger-ui:latest
  #   container_name: swagger-ui
  #   ports:
  #       - ${SWAGGER_PORT}:8080
  #   environment:
  #       API_URL: http://127.0.0.1:${POSTGREST_PORT}/      
  #   restart: unless-stopped
  #   networks:
  #     - gis-net
  #   depends_on:
  #     - postgrest

# Uncomment this if you want to persist the data.
volumes:
    pgadmin-data:

networks:
  gis-net:
    driver: bridge